name: archive

on: deployment_status

jobs:
    archive:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install archivenow
            - name: Archive pages
              run: |
                  archivenow --ia https://piracy.now.sh/
                  archivenow --ia https://piracy.now.sh/about/
                  archivenow --ia https://piracy.now.sh/security/
                  archivenow --ia https://piracy.now.sh/laws/
                  archivenow --ia https://piracy.now.sh/dead/
                  archivenow --ia https://piracy.netlify.app/
                  archivenow --ia https://piracy.netlify.app/about/
                  archivenow --ia https://piracy.netlify.app/security/
                  archivenow --ia https://piracy.netlify.app/laws/
                  archivenow --ia https://piracy.netlify.app/dead/
                  archivenow --ia https://maximousblk.github.io/piracy/
            - name: Fortune Cookie
              uses: vincetse/fortune-cookie-action@v4
