name: Check Links

on:
  push:
  schedule: 
    - cron: "0 0 1 */2 *"

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - name: Check Links
              uses: peter-evans/link-checker@v1.2.2
              with:
                args: -r *

            - name: Close Old Issue
              uses: bdougie/close-issues-based-on-label@master
              env:
                LABEL: bad links
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create New Issue
              uses: peter-evans/create-issue-from-file@v2
              with:
                title: Bad Links
                content-filepath: ./link-checker/out.md
                labels: bad links
